name: sprout_mobile_exam_serrano
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true