name: analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.13.1'
          channel: 'stable'

      - name: Dependencies
        run: flutter packages get

      - name: Environment Variables
        run: echo "" >> .env

      - name: Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze
